### ISSUE TITLE
Feature 15 : Admin user

### ISSUE THREAD

**Issue by clarzou** [cytronn/HETIC-G1-08#22]
- [x] The admin can manage the list of tags available

_to complete_

**Comment by CharlesMangwa** [comment]
I remember @LeoLeBras suggested a tool for that!

**Comment by clarzou** [comment]
Active admin?

**Comment by CharlesMangwa** [comment]
Exactly!

**Comment by LeoLeBras** [comment]
> https://activeadmin.info
