### ISSUE TITLE
Circle CI integration

### ISSUE THREAD

**Issue by LeoLeBras** [cytronn/HETIC-G1-08#5]
Currently, the CircleCI integration will show fixed/failed messages for all branches. 😢
@CharlesMangwa  @cytronn ?

**Comment by CharlesMangwa** [comment]
Tip: you can test your CircleCi build locally, before pushing :) -> https://circleci.com/docs/2.0/local-jobs/

ping: @LeoLeBras @cytronn @clarzou

**Comment by CharlesMangwa** [comment]
Fixed in d68f4d7.
